chore(app-server): change application server from uwsgi to gunicorn
adfinis/document-merge-service pull request #569
Opened 2022-11-23 14:06 UTC by fugal-dy

2022-12-09 09:50 UTC, open-dynaMIX requested changes
Nice work :tada:

Did you test this manually? We have no tests that would actually fail, if this doesn't work as expected. I think for this change it's important to - at least - locally verifiy, everything is working as expected.

2022-12-09 09:50 UTC, open-dynaMIX commented on cmd.sh
> +GUNICORN_WORKERS="${GUNICORN_WORKERS:-8}"
This should be documented in the `README.md` as well as `docker-compose.yml`.

2025-02-28 15:20 UTC, derrabauke commented
@fugal-dy @open-dynaMIX bump :up:

2025-02-28 15:24 UTC, open-dynaMIX commented
@derrabauke I think this is superseeded by #766.

2025-03-19 12:44 UTC, fugal-dy commented
> @derrabauke I think this is superseeded by #766.

Looks just like that. Closing.

2025-03-19 12:44 UTC, closed without merging