feat(filters): add configurable meta filter
adfinis/document-merge-service pull request #584
Opened 2023-01-24 13:35 UTC by Yelinz

problem in test, when selectivly running tests the settings are overriden and it works. when running the whole test suite the settings arent changed and fails

2023-01-24 14:58 UTC, winged requested changes
Nice work so far, but generally, I'm not sure if this is precisely the way to go. It seems like a rather fragile way to configure configurable meta filters - maybe let's discuss how this should work?

2023-01-24 14:58 UTC, winged commented on document_merge_service/api/filters.py
> +    )
This creates direct references, which will not change when you modify the settings during runtime of the tests. That's probably what you're seeing in CI

2023-01-26 08:46 UTC, winged commented
As discussed in-person: I'd suggest using the `JSONValueFilter` that we wrote in Caluma and is in use in Alexandria as well: https://github.com/projectcaluma/alexandria/blob/main/alexandria/core/filters.py#L12

Sadly, this creates yet another copy of the same filter. I think we should push towards factoring this out into a separate project / library, so it won't need to be copied around too much

2023-01-26 10:13 UTC, Yelinz commented
Implemented the filter, will be refactored out at a later date into a separate package

2023-01-26 15:40 UTC, czosel commented
Looks like this is still missing some test coverage:
```
document_merge_service/api/filters.py                                       40     23    42%   18-59, 63-70
```

2023-01-27 07:36 UTC, Yelinz commented
Forgot to add new test file

2023-01-27 08:02 UTC, czosel approved these changes
Just a little cleanup, otherwise LGTM

2023-01-27 08:02 UTC, czosel commented on document_merge_service/api/filters.py
> +        print(value)
This can probably be dropped

2023-01-27 08:19 UTC, Yelinz commented on document_merge_service/api/filters.py
> +        print(value)
Done

2023-01-27 08:37 UTC, czosel commented on document_merge_service/api/tests/test_filters.py
> +    print(url)
sorry, another print statement

2023-01-27 08:39 UTC, Yelinz commented on document_merge_service/api/tests/test_filters.py
> +    print(url)
removed, didnt catch that :(

2023-01-27 08:47 UTC, czosel approved these changes

2023-01-27 08:51 UTC, merged