feat: allow conversion of docx files to pdf using a new convert endpoint
adfinis/document-merge-service pull request #622
Opened 2023-07-11 14:36 UTC by StephanH90

Adds a new `convert` endpoint which can be used with a post request to submit a docx file which is then converted to pdf and sent back with the response.

2023-07-13 13:19 UTC, StephanH90 commented
there seems to be an issue when im using it in camac, Im investigating.

2023-07-13 13:39 UTC, StephanH90 commented
Turns out that this is failing in camac-ng because the `group` attribute on the template was removed and camac-ng still tries to write this. So it isn't an issue with this MR.

2023-07-17 09:42 UTC, winged requested changes
Nice work! I like!

Just figured that we shouldn't limit ourselves too much on the input formats

2023-07-17 09:42 UTC, winged commented on document_merge_service/api/views.py
> +        ):
This could possibly be extended to support more office formats (specifically, ODT as LibreOffice's native format)

2023-08-02 14:58 UTC, winged approved these changes

2023-08-03 05:43 UTC, merged